### ISSUE TITLE
Reason behind version 3.0?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/grokcore.annotation#10]
The change log contains a version number jump from 1.6 to 3.0 but the changes for 3.0 ("Rearrange tests such that Travis CI can pick up all functional tests too.")  do not seem to require a new major version.

Are there some more change log entries missing? Or what is the reason behind this change?

**Comment by janwijbrand** [comment]
This was a (perhaps/probably misguided) attempt to get all the version numbers of `grokcore.*` consistent now that they have Python 3 support.

**Comment by icemac** [comment]
Okay, no problem.
